# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "2025 THM Advent of Cyber"
description:	       "Michael B's 2025 THM Advent of Cyber Write up blog"
author:              "Michael B"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
  path: rss-feed.xml
